<?php
require_once '..\..\..\..\utility.php';
$i = 0;
$txt[$i++] = "\\(\\left|{\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right)}\\right| = \\left(1 - r\\right)^{n} \\prod\\limits_{k=1}^{n - 1} k!\\tag*{Eq[0]}\\)";
$txt[$i++] = "\\(\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right) \\times [i:n,j]\\left(\\left(-1\\right)^{i + j} {\\binom{j + 1}{i + 1}}\\right) = \\left(\\begin{array}{c}{[j]\\sum\\limits_{k=0}^{n - 1} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}}}\\\\{[i:n - 1,j]\\sum\\limits_{k=0}^{n - 1} \\left(-1\\right)^{j + k} \\left(k + 1\\right)^{i + 1} {\\binom{j + 1}{k + 1}}}\\end{array}\\right)\\tag*{Eq[1]}\\)";
$txt[$i++] = "\\(\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right) \\times [i:n,j]\\left(\\left(-1\\right)^{i + j} {\\binom{j + 1}{i + 1}}\\right) = \\left(\\begin{array}{c}{[j]\\sum\\limits_{k=0}^{n - 1} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}}}\\\\{[i:n - 1,j]\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(k + 1\\right)^{i + 1} {\\binom{j + 1}{k + 1}}}\\end{array}\\right)\\tag*{Eq[2]}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} = \\frac{\\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j + k + 1} k^{i + 1} {\\binom{j + 1}{k}}}{\\left(j + 1\\right)!}\\tag*{Eq[3]}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)! = \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j + k + 1} k^{i + 1} {\\binom{j + 1}{k}}\\tag*{Eq[4]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j + k + 1} k^{i + 1} {\\binom{j + 1}{k}} = \\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!\\tag*{Eq[5]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j + k + 1} k^{i + 1} {\\binom{j + 1}{k}} = \\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!\\tag*{Eq[6]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le n - 2}}{\\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j + k + 1} k^{i + 1} {\\binom{j + 1}{k}} = \\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!}\\tag*{Eq[7]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(k + 1\\right)^{i + 1} {\\binom{j + 1}{k + 1}} = \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j + k + 1} k^{i + 1} {\\binom{j + 1}{k}}\\tag*{Eq[8]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le n - 2}}{\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(k + 1\\right)^{i + 1} {\\binom{j + 1}{k + 1}} = \\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!}\\tag*{Eq[9]}\\)";
$txt[$i++] = "\\(\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right) \\times [i:n,j]\\left(\\left(-1\\right)^{i + j} {\\binom{j + 1}{i + 1}}\\right) = \\left(\\begin{array}{c}{[j]\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}}}\\\\{[i:n - 1,j]\\left(\\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!\\right)}\\end{array}\\right)\\tag*{Eq.equation}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j + k + 1} \\left(1 - r^{k}\\right) {\\binom{j + 1}{k}}\\tag*{Eq[10]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = - \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} {\\binom{j + 1}{k}} + \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} r^{k} {\\binom{j + 1}{k}}\\tag*{Eq[11]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = \\left(-1\\right)^{j} \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{k} r^{k} {\\binom{j + 1}{k}} - \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} {\\binom{j + 1}{k}}\\tag*{Eq[12]}\\)";
$txt[$i++] = "\\(\\left(r - 1\\right)^{j + 1} = \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j + k + 1} r^{k} {\\binom{j + 1}{k}}\\tag*{Eq[13]}\\)";
$txt[$i++] = "\\(\\left(r - 1\\right)^{j + 1} = - \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} r^{k} {\\binom{j + 1}{k}}\\tag*{Eq[14]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = - \\left(r - 1\\right)^{j + 1} - \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} {\\binom{j + 1}{k}} - \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} r^{k} {\\binom{j + 1}{k}} + \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} r^{k} {\\binom{j + 1}{k}}\\tag*{Eq[15]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = - \\left(-1\\right)^{j} - \\left(r - 1\\right)^{j + 1} - \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} {\\binom{j + 1}{k}}\\tag*{Eq[16]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = - \\left(-1\\right)^{j} \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{k} {\\binom{j + 1}{k}} - \\left(-1\\right)^{j} - \\left(r - 1\\right)^{j + 1}\\tag*{Eq[17]}\\)";
$txt[$i++] = "\\(0 = \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j + k + 1} {\\binom{j + 1}{k}}\\tag*{Eq[18]}\\)";
$txt[$i++] = "\\(0 = \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{j} \\left(-1\\right)^{k} {\\binom{j + 1}{k}}\\tag*{Eq[19]}\\)";
$txt[$i++] = "\\(0 = \\left(-1\\right)^{j} \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{k} {\\binom{j + 1}{k}}\\tag*{Eq[20]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = \\left(-1\\right)^{j} \\sum\\limits_{k=0}^{j + 1} \\left(-1\\right)^{k} {\\binom{j + 1}{k}} - \\left(-1\\right)^{j} \\sum\\limits_{k=1}^{j + 1} \\left(-1\\right)^{k} {\\binom{j + 1}{k}} - \\left(-1\\right)^{j} - \\left(r - 1\\right)^{j + 1}\\tag*{Eq[21]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{k=0}^{j} \\left(-1\\right)^{j + k} \\left(1 - r^{k + 1}\\right) {\\binom{j + 1}{k + 1}} = - \\left(r - 1\\right)^{j + 1}\\tag*{Eq[22]}\\)";
$txt[$i++] = "\\(\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right) \\times [i:n,j]\\left(\\left(-1\\right)^{i + j} {\\binom{j + 1}{i + 1}}\\right) = \\left(\\begin{array}{c}{[j]\\left(- \\left(r - 1\\right)^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(\\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!\\right)}\\end{array}\\right)\\tag*{Eq[23]}\\)";
$txt[$i++] = "\\(Shift\\left(n, 0, n - 1\\right) \\times \\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right) \\times [i:n,j]\\left(\\left(-1\\right)^{i + j} {\\binom{j + 1}{i + 1}}\\right) = \\left(\\begin{array}{c}{[i:n - 1,j]\\left(\\left\\{\\begin{matrix}{i + 1}\\\\{j + 1}\\end{matrix}\\right\\} \\left(j + 1\\right)!\\right)}\\\\{[j]\\left(- \\left(r - 1\\right)^{j + 1}\\right)}\\end{array}\\right)\\tag*{Eq[24]}\\)";
$txt[$i++] = "\\(\\left(-1\\right)^{n + 1} \\left|{\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right)}\\right| = \\prod\\limits_{k=0}^{n - 1} \\begin{cases} \\left(k + 1\\right)! & \\text{if}\\: k < n - 1 \\\\- \\left(r - 1\\right)^{k + 1} & \\text{if}\\: k < n \\end{cases}\\tag*{Eq[25]}\\)";
$txt[$i++] = "\\(\\left(-1\\right)^{n + 1} \\left|{\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right)}\\right| = - \\left(r - 1\\right)^{n} \\prod\\limits_{k=0}^{n - 2} \\left(k + 1\\right)!\\tag*{Eq[26]}\\)";
$txt[$i++] = "\\(\\left|{\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right)}\\right| = - \\left(-1\\right)^{n + 1} \\left(r - 1\\right)^{n} \\prod\\limits_{k=0}^{n - 2} \\left(k + 1\\right)!\\tag*{Eq[27]}\\)";
$txt[$i++] = "\\(\\left|{\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right)}\\right| = \\left(1 - r\\right)^{n} \\prod\\limits_{k=0}^{n - 2} \\left(k + 1\\right)!\\tag*{Eq[28]}\\)";
$txt[$i++] = "\\(\\left|{\\left(\\begin{array}{c}{[j]\\left(1 - r^{j + 1}\\right)}\\\\{[i:n - 1,j]\\left(j + 1\\right)^{i + 1}}\\end{array}\\right)}\\right| = \\left(1 - r\\right)^{n} \\prod\\limits_{k=1}^{n - 1} k!\\tag*{Eq[0]}\\)";
render(__FILE__, $txt);
?>        

