<?php
require_once '..\..\..\..\..\utility.php';
$i = 0;
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n + 1}\\\\{k + 1}\\end{matrix}\\right\\} = \\left(k + 1\\right) \\left\\{\\begin{matrix}{n}\\\\{k + 1}\\end{matrix}\\right\\} + \\left\\{\\begin{matrix}{n}\\\\{k}\\end{matrix}\\right\\}\\tag*{?=>Eq[0]}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n + 1}\\\\{k + 1}\\end{matrix}\\right\\} = \\left|{\\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right] \\right\\} \\right\\}}\\right|\\tag*{Eq.stirling2}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n}\\\\{k}\\end{matrix}\\right\\} = \\left|{\\left\\{\\left. \\left\\{*{x}_{0:k}\\right\\}  \\right| {x}_{0:k} \\in \\left\\{\\left. {x}_{0:k} \\right| \\forall_{\\substack{0 \\le i < k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k - 1} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {x}_{i} = \\left[0; n\\right) \\right\\} \\right\\}}\\right|\\tag*{Eq.stirling0}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n}\\\\{k + 1}\\end{matrix}\\right\\} = \\left|{\\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right) \\right\\} \\right\\}}\\right|\\tag*{Eq.stirling1}\\)";
$txt[$i++] = "\\(s_{2} = \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right] \\right\\} \\right\\}\\tag*{Eq[1]}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n + 1}\\\\{k + 1}\\end{matrix}\\right\\} = \\left|{s_{2}}\\right|\\tag*{Eq.stirling2}\\)";
$txt[$i++] = "\\(s'_{2} = \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right] \\right\\}\\tag*{Eq[2]}\\)";
$txt[$i++] = "\\(s_{2} = \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{2} \\right\\}\\tag*{Eq.s2_definition}\\)";
$txt[$i++] = "\\(s_{0} = \\left\\{\\left. \\left\\{*{x}_{0:k}\\right\\}  \\right| {x}_{0:k} \\in \\left\\{\\left. {x}_{0:k} \\right| \\forall_{\\substack{0 \\le i < k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k - 1} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {x}_{i} = \\left[0; n\\right) \\right\\} \\right\\}\\tag*{Eq[3]}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n}\\\\{k}\\end{matrix}\\right\\} = \\left|{s_{0}}\\right|\\tag*{Eq.stirling0}\\)";
$txt[$i++] = "\\(s'_{0} = \\left\\{\\left. {x}_{0:k} \\right| \\forall_{\\substack{0 \\le i < k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k - 1} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {x}_{i} = \\left[0; n\\right) \\right\\}\\tag*{Eq[4]}\\)";
$txt[$i++] = "\\(s_{0} = \\left\\{\\left. \\left\\{*{x}_{0:k}\\right\\}  \\right| {x}_{0:k} \\in s'_{0} \\right\\}\\tag*{Eq[5]}\\)";
$txt[$i++] = "\\(s_{1} = \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right) \\right\\} \\right\\}\\tag*{Eq[6]}\\)";
$txt[$i++] = "\\(\\left\\{\\begin{matrix}{n}\\\\{k + 1}\\end{matrix}\\right\\} = \\left|{s_{1}}\\right|\\tag*{Eq.stirling1}\\)";
$txt[$i++] = "\\(s'_{1} = \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right) \\right\\}\\tag*{Eq[7]}\\)";
$txt[$i++] = "\\(s_{1} = \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{1} \\right\\}\\tag*{Eq[8]}\\)";
$txt[$i++] = "\\(\\left\\{\\left. e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in s_{0} \\right\\} \\subset s_{2}\\tag*{Eq[9]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{0}}}{e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{2}}\\tag*{Eq[10]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\left\\{\\left\\{n\\right\\}\\right\\} \\cup \\left\\{*{x}_{0:k}\\right\\}  \\in s_{2}}\\tag*{Eq[11]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\left\\{\\left\\{n\\right\\}\\right\\} \\cup \\left\\{*{x}_{0:k}\\right\\}  \\in \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{2} \\right\\}}\\tag*{Eq[12]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]}\\tag*{Eq.s2_quote_definition}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\forall_{\\substack{0 \\le i < k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k - 1} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {x}_{i} = \\left[0; n\\right)}\\tag*{Eq[13]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right)}\\tag*{Eq[14]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i < k\\\\{x}_{0:k} \\in s'_{0}}}{\\left|{{x}_{i}}\\right| > 0}\\tag*{Eq[15]}\\)\\(\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\sum\\limits_{i=0}^{k - 1} \\left|{{x}_{i}}\\right| = n}\\tag*{Eq[16]}\\)\\(\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\bigcup\\limits_{i=0}^{k - 1} {x}_{i} = \\left[0; n\\right)}\\tag*{Eq[17]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{{x}_{k} = \\left\\{n\\right\\}}\\tag*{Eq[18]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]}}\\tag*{Eq[19]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\left\\{{x}_{k}\\right\\} = \\left\\{\\left\\{n\\right\\}\\right\\}}\\tag*{Eq[20]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\left\\{*{x}_{0:k + 1}\\right\\}  = \\left\\{\\left\\{n\\right\\}\\right\\} \\cup \\left\\{*{x}_{0:k}\\right\\} }\\tag*{Eq[21]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\left\\{*{x}_{0:k + 1}\\right\\}  \\in \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{2} \\right\\}}}\\tag*{Eq[22]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]}}\\tag*{Eq[23]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\left|{{x}_{k}}\\right| = 1}\\tag*{Eq[24]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\left|{{x}_{k}}\\right| > 0}\\tag*{Eq[25]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1}}\\tag*{Eq[26]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k} \\in s'_{0}}}{\\left|{{x}_{i}}\\right| > 0}}\\tag*{Eq[27]}\\)";
$txt[$i++] = "\\(\\exists_{{x}_{k}}{\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]}}\\tag*{Eq[23]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x}_{i}}\\right| > 0}\\tag*{Eq.x_abs_positive_s1}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n}\\tag*{Eq.x_abs_sum_s1}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right)}\\tag*{Eq.x_union_s1}\\)";
$txt[$i++] = "\\({x'}_{i} = \\begin{cases} \\left\\{n\\right\\} \\cup {x}_{i} & \\text{if}\\: i = j \\\\{x}_{i} & \\text{else} \\end{cases}\\tag*{Eq.x_quote_definition}\\)";
$txt[$i++] = "\\(\\left\\{\\left. \\left\\{*x'\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{1} \\right\\} \\subset s_{2}\\tag*{Eq.x_quote_set_in_s2}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  \\in s_{2}}\\tag*{Eq[28]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  \\in \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{2} \\right\\}}\\tag*{Eq[29]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x'}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x'}_{i} = \\left[0; n\\right]}\\tag*{Eq[30]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x'}_{i} = \\left[0; n\\right]\\wedge \\left|{{x'}_{i}}\\right| > 0}\\tag*{Eq[31]}\\)";
$txt[$i++] = "\\(\\bigcup\\limits_{i=0}^{k} {x'}_{i} = \\left\\{n\\right\\} \\cup \\bigcup\\limits_{i=0}^{k} {x}_{i}\\tag*{Eq[32]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\bigcup\\limits_{i=0}^{k} {x'}_{i} = \\left[0; n\\right]}\\tag*{Eq[33]}\\)";
$txt[$i++] = "\\(\\left|{{x'}_{i}}\\right| = \\begin{cases} \\left|{\\left\\{n\\right\\} \\cup {x}_{i}}\\right| & \\text{if}\\: i = j \\\\\\left|{{x}_{i}}\\right| & \\text{else} \\end{cases}\\tag*{Eq[34]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| = - \\left|{{x}_{j}}\\right| + \\left|{\\left\\{n\\right\\} \\cup {x}_{j}}\\right| + \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right|\\tag*{Eq[35]}\\)";
$txt[$i++] = "\\(\\left|{\\left\\{n\\right\\} \\cup {x}_{j}}\\right| \\leq \\left|{{x}_{j}}\\right| + 1\\tag*{Eq[36]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| \\leq \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| + 1\\tag*{Eq[37]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| \\leq n + 1}\\tag*{Eq[38]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left|{\\bigcup\\limits_{i=0}^{k} {x'}_{i}}\\right| = n + 1}\\tag*{Eq[39]}\\)";
$txt[$i++] = "\\(\\left|{\\bigcup\\limits_{i=0}^{k} {x'}_{i}}\\right| \\leq \\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right|\\tag*{Eq[40]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| \\geq n + 1}\\tag*{Eq[41]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| = n + 1}\\tag*{Eq[42]}\\)";
$txt[$i++] = "\\(\\left|{{x'}_{j}}\\right| = \\left|{\\left\\{n\\right\\} \\cup {x}_{j}}\\right|\\tag*{Eq[43]}\\)\\(\\forall_{\\substack{i \\left| i \\neq j \\right.}}{\\left|{{x'}_{i}}\\right| = \\left|{{x}_{i}}\\right|}\\tag*{Eq[44]}\\)";
$txt[$i++] = "\\(\\left|{\\left\\{n\\right\\} \\cup {x}_{j}}\\right| \\geq \\left|{{x}_{j}}\\right|\\tag*{Eq[45]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left|{\\left\\{n\\right\\} \\cup {x}_{j}}\\right| > 0}\\tag*{Eq[46]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x'}_{j}}\\right| > 0}\\tag*{Eq[47]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x'}_{i}}\\right| > 0}\\tag*{Eq[48]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x'}_{i}}\\right| > 0}\\tag*{Eq[49]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x'}_{i} = \\left[0; n\\right]\\wedge \\left|{{x'}_{i}}\\right| > 0}\\tag*{Eq[31]}\\)";
$txt[$i++] = "\\(x' = [i:k + 1]\\begin{cases} \\left\\{n\\right\\} \\cup {x}_{i} & \\text{if}\\: i = j \\\\{x}_{i} & \\text{else} \\end{cases}\\tag*{Eq.x_quote_definition}\\)";
$txt[$i++] = "\\({A}_{j} = \\left\\{\\left. \\left\\{*x'\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{1} \\right\\}\\tag*{Eq.A_definition}\\)";
$txt[$i++] = "\\({A}_{j} \\subset s_{2}\\tag*{Eq[50]}\\)";
$txt[$i++] = "\\(\\bigcup_{j} {A}_{j} \\subset \\bigcup_{j} s_{2}\\tag*{Eq[51]}\\)";
$txt[$i++] = "\\(B = \\left\\{\\left. e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in s_{0} \\right\\}\\tag*{Eq.B_definition}\\)";
$txt[$i++] = "\\(B \\subset s_{2}\\tag*{Eq[52]}\\)";
$txt[$i++] = "\\(B \\cup {A}_{j} \\subset s_{2}\\tag*{Eq[53]}\\)";
$txt[$i++] = "\\(s_{2} = \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\} \\cup \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}\\tag*{Eq[54]}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\} \\subset B\\tag*{Eq.subset_B}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}\\supset B\\tag*{Eq.supset_B}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\} \\subset \\bigcup_{j} {A}_{j}\\tag*{Eq.subset_A}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}\\supset {A}_{j}\\tag*{Eq.supset_A}\\)";
$txt[$i++] = "\\(\\left|{s_{2}}\\right| = \\left|{\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}}\\right| + \\left|{\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}}\\right|\\tag*{Eq.s2_abs}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}\\supset \\left\\{\\left. \\left\\{*x'\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{1} \\right\\}\\tag*{Eq[55]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  \\in s_{2}\\wedge \\left\\{n\\right\\} \\not\\in \\left\\{*x'\\right\\} }\\tag*{Eq[56]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  \\in s_{2}}\\tag*{Eq[28]}\\)\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{n\\right\\} \\not\\in \\left\\{*x'\\right\\} }\\tag*{Eq[57]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{n\\right\\} \\in \\left\\{*x'\\right\\} }\\tag*{~Eq[58]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{n\\right\\} = {x'}_{i}}\\tag*{~Eq[59]}\\)";
$txt[$i++] = "\\({x'}_{j} = \\left\\{n\\right\\} \\cup {x}_{j}\\tag*{Eq[60]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{{x'}_{i} \\cap {x'}_{j} = \\left\\{n\\right\\}}\\tag*{~Eq[61]}\\)";
$txt[$i++] = "\\(\\left|{{x'}_{i} \\cup {x'}_{j}}\\right| = \\left|{{x'}_{i}}\\right| + \\left|{{x'}_{j}}\\right| - \\left|{{x'}_{i} \\cap {x'}_{j}}\\right|\\tag*{Eq[62]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x'}_{i} \\cup {x'}_{j}}\\right| = \\left|{{x'}_{i}}\\right| + \\left|{{x'}_{j}}\\right| - 1}\\tag*{~Eq[63]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x'}_{i} \\cup {x'}_{j}}\\right| < \\left|{{x'}_{i}}\\right| + \\left|{{x'}_{j}}\\right|}\\tag*{~Eq.set_size_inequality}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{i, j\\right\\}} {x'}_{i} \\cup \\bigcup\\limits_{i \\in \\left[0; k\\right] \\cap \\left\\{i, j\\right\\}} {x'}_{i} = \\left[0; n\\right]}\\tag*{Eq[64]}\\)";
$txt[$i++] = "\\(\\left|{\\bigcup\\limits_{i=0}^{k} {x'}_{i}}\\right| \\leq \\left|{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{i, j\\right\\}} {x'}_{i}}\\right| + \\left|{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\cap \\left\\{i, j\\right\\}} {x'}_{i}}\\right|\\tag*{Eq[65]}\\)";
$txt[$i++] = "\\(\\left|{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{i, j\\right\\}} {x'}_{i}}\\right| \\leq \\sum\\limits_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{i, j\\right\\}}} \\left|{{x'}_{i}}\\right|\\tag*{Eq[66]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left|{{x'}_{i} \\cup {x'}_{j}}\\right| + \\left|{\\bigcup\\limits_{i=0}^{k} {x'}_{i}}\\right| < \\left|{{x'}_{i}}\\right| + \\left|{{x'}_{j}}\\right| + \\left|{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\cap \\left\\{i, j\\right\\}} {x'}_{i}}\\right| + \\sum\\limits_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{i, j\\right\\}}} \\left|{{x'}_{i}}\\right|}\\tag*{~Eq[67]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left|{\\bigcup\\limits_{i=0}^{k} {x'}_{i}}\\right| < \\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right|}\\tag*{~Eq[68]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{n + 1 < \\sum\\limits_{i=0}^{k} \\left|{{x'}_{i}}\\right|}\\tag*{~Eq[69]}\\)";
$txt[$i++] = "\\(\\text{False}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  \\in s_{2}\\wedge \\left\\{n\\right\\} \\not\\in \\left\\{*x'\\right\\} }\\tag*{Eq[56]}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}\\supset \\left\\{\\left. e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in s_{0} \\right\\}\\tag*{Eq[70]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{0}}}{e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{2}}\\tag*{Eq[10]}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\} \\subset \\left\\{\\left. e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in s_{0} \\right\\}\\tag*{Eq[71]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}}}{\\exists_{\\substack{e \\in s_{0}}}{a = e \\cup \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq[72]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}}}{\\exists_{\\substack{e \\in s_{0}}}{a \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} = e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq.subset_B_definition}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{0}}}{\\left\\{n\\right\\} \\not\\in e}\\tag*{Eq.plausible_notcontains}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\left\\{n\\right\\} \\not\\in \\left\\{*{x}_{0:k}\\right\\} }\\tag*{Eq[73]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\left\\{n\\right\\} \\in \\left\\{*{x}_{0:k}\\right\\} }\\tag*{~Eq[74]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i < k\\\\{x}_{0:k} \\in s'_{0}}}{\\left\\{n\\right\\} = {x}_{i}}\\tag*{~Eq[75]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k} \\in s'_{0}}}{\\bigcup\\limits_{i=0}^{k - 1} {x}_{i} = \\left[0; n\\right]}\\tag*{~Eq[76]}\\)";
$txt[$i++] = "\\(\\text{False}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{0}}}{e \\cap \\left\\{\\left\\{n\\right\\}\\right\\} = \\emptyset}\\tag*{Eq[77]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{0}}}{e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} = e}\\tag*{Eq.s0_complement_n}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}}}{a \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{0}}\\tag*{Eq[78]}\\)";
$txt[$i++] = "\\(s_{2, n} = \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}\\tag*{Eq.s2_n_definition}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{2, n}}}{e \\in s_{2}\\wedge \\left\\{n\\right\\} \\in e}\\tag*{Eq[79]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{2, n}}}{e \\in s_{2}}\\tag*{Eq[80]}\\)\\(\\forall_{\\substack{e \\in s_{2, n}}}{\\left\\{n\\right\\} \\in e}\\tag*{Eq[81]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{2, n}}}{e \\in \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{2} \\right\\}}\\tag*{Eq[82]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{e = \\left\\{*{x}_{0:k + 1}\\right\\} }}\\tag*{Eq.s2_n_assertion}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{\\left\\{n\\right\\} \\in \\left\\{*{x}_{0:k + 1}\\right\\} }\\tag*{Eq[83]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left\\{n\\right\\} = {x}_{i}}\\tag*{Eq[84]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{{x}_{j} = \\left\\{n\\right\\}}\\tag*{Eq.x_j_definition}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left|{{x}_{i}}\\right| > 0}\\tag*{Eq.x_abs_positive_s2}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{\\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1}\\tag*{Eq.x_abs_sum_s2}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{\\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]}\\tag*{Eq.x_union_s2}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\bigcup\\limits_{i=0}^{k} {x}_{i} \\setminus {x}_{j} = \\left[0; n\\right)}\\tag*{Eq[85]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}} {x}_{i} = \\left[0; n\\right)}\\tag*{Eq[86]}\\)";
$txt[$i++] = "\\({\\tilde{x}}_{i} = \\begin{cases} {x}_{i} & \\text{if}\\: i < j \\\\{x}_{i + 1} & \\text{else} \\end{cases}\\tag*{Eq.x_tilde_definition}\\)";
$txt[$i++] = "\\(\\bigcup\\limits_{i=0}^{k - 1} {\\tilde{x}}_{i} = \\bigcup\\limits_{i=0}^{j - 1} {x}_{i} \\cup \\bigcup\\limits_{i=j}^{k - 1} {x}_{i + 1}\\tag*{Eq[87]}\\)";
$txt[$i++] = "\\(\\bigcup\\limits_{i=0}^{k - 1} {\\tilde{x}}_{i} = \\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}} {x}_{i}\\tag*{Eq[88]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\bigcup\\limits_{i=0}^{k - 1} {\\tilde{x}}_{i} = \\left[0; n\\right)}\\tag*{Eq.x_tilde_union}\\)";
$txt[$i++] = "\\(\\left|{{\\tilde{x}}_{i}}\\right| = \\begin{cases} \\left|{{x}_{i}}\\right| & \\text{if}\\: i < j \\\\\\left|{{x}_{i + 1}}\\right| & \\text{else} \\end{cases}\\tag*{Eq.x_tilde_abs}\\)";
$txt[$i++] = "\\(\\sum\\limits_{i=0}^{k - 1} \\left|{{\\tilde{x}}_{i}}\\right| = \\sum\\limits_{i=j}^{k - 1} \\left|{{x}_{i + 1}}\\right| + \\sum\\limits_{i=0}^{j - 1} \\left|{{x}_{i}}\\right|\\tag*{Eq[89]}\\)";
$txt[$i++] = "\\(\\sum\\limits_{i=0}^{k - 1} \\left|{{\\tilde{x}}_{i}}\\right| = - \\left|{{x}_{j}}\\right| + \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right|\\tag*{Eq[90]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\sum\\limits_{i=0}^{k - 1} \\left|{{\\tilde{x}}_{i}}\\right| = n}\\tag*{Eq.x_tilde_abs_sum}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{i \\left| i < j \\right.}}{\\left|{{\\tilde{x}}_{i}}\\right| = \\left|{{x}_{i}}\\right|}\\tag*{Eq[91]}\\)\\(\\forall_{\\substack{i \\left| i \\geq j \\right.}}{\\left|{{\\tilde{x}}_{i}}\\right| = \\left|{{x}_{i + 1}}\\right|}\\tag*{Eq[92]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i < j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left|{{\\tilde{x}}_{i}}\\right| > 0}\\tag*{Eq[93]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{j \\le i < k\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left|{{\\tilde{x}}_{i}}\\right| > 0}\\tag*{Eq[94]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{\\left|{{\\tilde{x}}_{i}}\\right| > 0}\\tag*{Eq[95]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\sum\\limits_{i=0}^{k - 1} \\left|{{\\tilde{x}}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {\\tilde{x}}_{i} = \\left[0; n\\right)\\wedge \\left|{{\\tilde{x}}_{i}}\\right| > 0}\\tag*{Eq[96]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\tilde{x} \\in s'_{0}}\\tag*{Eq[97]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\forall_{\\substack{0 \\le i < k}}{\\left|{{\\tilde{x}}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k - 1} \\left|{{\\tilde{x}}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {\\tilde{x}}_{i} = \\left[0; n\\right)}\\tag*{Eq[98]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\sum\\limits_{i=0}^{k - 1} \\left|{{\\tilde{x}}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k - 1} {\\tilde{x}}_{i} = \\left[0; n\\right)\\wedge \\left|{{\\tilde{x}}_{i}}\\right| > 0}\\tag*{Eq[96]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left\\{*\\tilde{x}\\right\\}  \\in s_{0}}\\tag*{Eq.x_tilde_set_in_s0}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left\\{*\\tilde{x}\\right\\}  \\in \\left\\{\\left. \\left\\{*{x}_{0:k}\\right\\}  \\right| {x}_{0:k} \\in s'_{0} \\right\\}}\\tag*{Eq[99]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\tilde{x} \\in s'_{0}}\\tag*{Eq[97]}\\)";
$txt[$i++] = "\\(\\left\\{*\\tilde{x}\\right\\}  = \\left\\{*{x}_{0:k + 1}\\right\\}  \\setminus \\left\\{{x}_{j}\\right\\}\\tag*{Eq[100]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j\\\\{x}_{0:k + 1} \\in s'_{2}}}{\\left\\{*\\tilde{x}\\right\\}  = \\left\\{*{x}_{0:k + 1}\\right\\}  \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}\\tag*{Eq[101]}\\)";
$txt[$i++] = "\\(\\exists_{j}{\\forall_{\\substack{e \\in s_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{2}}}{\\left\\{*\\tilde{x}\\right\\}  = e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}}}\\tag*{Eq[102]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{2, n}}}{e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{0}}\\tag*{Eq[103]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\}}}{e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{0}}\\tag*{Eq[78]}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\} \\subset \\bigcup_{j} \\left\\{\\left. \\left\\{*x'\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{1} \\right\\}\\tag*{Eq[104]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j}}{a = \\left\\{*x'\\right\\} }}\\tag*{Eq[105]}\\)";
$txt[$i++] = "\\(\\hat{s}_{2, n} = \\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}\\tag*{Eq[106]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in \\hat{s}_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j}}{a = \\left\\{*x'\\right\\} }}\\tag*{Eq.s2_hat_n_assertion}\\)";
$txt[$i++] = "\\(\\hat{s}_{2, n} = \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]\\wedge \\left\\{n\\right\\} \\not\\in \\left\\{*{x}_{0:k + 1}\\right\\}  \\right\\} \\right\\}\\tag*{Eq[107]}\\)";
$txt[$i++] = "\\(s'_{2, n} = \\left\\{\\left. {x}_{0:k + 1} \\right| \\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]\\wedge \\left\\{n\\right\\} \\not\\in \\left\\{*{x}_{0:k + 1}\\right\\}  \\right\\}\\tag*{Eq[108]}\\)";
$txt[$i++] = "\\(\\hat{s}_{2, n} = \\left\\{\\left. \\left\\{*{x}_{0:k + 1}\\right\\}  \\right| {x}_{0:k + 1} \\in s'_{2, n} \\right\\}\\tag*{Eq[109]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s'_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j}}{\\left\\{*a\\right\\}  = \\left\\{*x'\\right\\} }}\\tag*{Eq.s2_hat_n_hypothesis}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{x}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1\\wedge \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]\\wedge \\left\\{n\\right\\} \\not\\in \\left\\{*{x}_{0:k + 1}\\right\\} }\\tag*{Eq[110]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{2, n}}}{\\left|{{x}_{i}}\\right| > 0}\\tag*{Eq.x_abs_positive_s2_n}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\sum\\limits_{i=0}^{k} \\left|{{x}_{i}}\\right| = n + 1}\\tag*{Eq.x_abs_sum_s2_n}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\bigcup\\limits_{i=0}^{k} {x}_{i} = \\left[0; n\\right]}\\tag*{Eq.x_union_s2_n}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\left\\{n\\right\\} \\not\\in \\left\\{*{x}_{0:k + 1}\\right\\} }\\tag*{Eq.n_not_in_x}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{2, n}}}{\\left\\{n\\right\\} \\neq {x}_{i}}\\tag*{Eq[111]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\left\\{n\\right\\} \\neq {x}_{j}}\\tag*{Eq.x_j_inequality}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{n \\in \\bigcup\\limits_{i=0}^{k} {x}_{i}}\\tag*{Eq[112]}\\)";
$txt[$i++] = "\\(\\text{True}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{\\substack{0 \\le i \\le k}}{n \\in {x}_{i}}}\\tag*{Eq[113]}\\)";
$txt[$i++] = "\\({\\hat{x}}_{i} = \\begin{cases} {x}_{i} \\setminus \\left\\{n\\right\\} & \\text{if}\\: i = j \\\\{x}_{i} & \\text{else} \\end{cases}\\tag*{Eq.x_hat_definition}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{n \\in {x}_{j}}}\\tag*{Eq[114]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\left\\{n\\right\\} \\subset {x}_{j}}}\\tag*{Eq.x_j_subset}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{{x}_{j} \\setminus \\left\\{n\\right\\} \\neq \\emptyset}}\\tag*{Eq[115]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\left|{{x}_{j} \\setminus \\left\\{n\\right\\}}\\right| > 0}}\\tag*{Eq[116]}\\)";
$txt[$i++] = "\\(\\left|{{\\hat{x}}_{i}}\\right| = \\begin{cases} \\left|{{x}_{i} \\setminus \\left\\{n\\right\\}}\\right| & \\text{if}\\: i = j \\\\\\left|{{x}_{i}}\\right| & \\text{else} \\end{cases}\\tag*{Eq.x_hat_abs}\\)";
$txt[$i++] = "\\(\\left|{{\\hat{x}}_{j}}\\right| = \\left|{{x}_{j} \\setminus \\left\\{n\\right\\}}\\right|\\tag*{Eq[117]}\\)\\(\\forall_{\\substack{i \\left| i \\neq j \\right.}}{\\left|{{\\hat{x}}_{i}}\\right| = \\left|{{x}_{i}}\\right|}\\tag*{Eq[118]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{2, n}}}{\\left|{{\\hat{x}}_{i}}\\right| > 0}\\tag*{Eq[119]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\left|{{\\hat{x}}_{j}}\\right| > 0}}\\tag*{Eq[120]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{\\hat{x}}_{i}}\\right| > 0}}}\\tag*{Eq.x_hat_abs_positive}\\)";
$txt[$i++] = "\\(\\bigcup\\limits_{i=0}^{k} {\\hat{x}}_{i} = \\left({x}_{j} \\setminus \\left\\{n\\right\\}\\right) \\cup \\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}} {x}_{i}\\tag*{Eq.x_hat_union}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\bigcup\\limits_{i=0}^{k} {x}_{i} \\setminus \\left\\{n\\right\\} = \\left[0; n\\right)}\\tag*{Eq.x_union_complement}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{j \\in \\left[0; k\\right] \\setminus \\left\\{i\\right\\}\\\\0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{2, n}}}{{x}_{i} \\cap {x}_{j} = \\emptyset}\\tag*{Eq[121]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{2, n}}}{{x}_{i} \\cap {x}_{j} = \\emptyset}\\tag*{Eq[122]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\forall_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{{x}_{i} \\setminus \\left\\{n\\right\\} = {x}_{i}}}}\\tag*{Eq.x_complement_n}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}} {x}_{i} \\setminus \\left\\{n\\right\\} = \\bigcup\\limits_{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}} {x}_{i}}}\\tag*{Eq[123]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\bigcup\\limits_{i=0}^{k} {\\hat{x}}_{i} = \\bigcup\\limits_{i=0}^{k} {x}_{i} \\setminus \\left\\{n\\right\\}}}\\tag*{Eq[124]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\bigcup\\limits_{i=0}^{k} {\\hat{x}}_{i} = \\left[0; n\\right)}}\\tag*{Eq.x_hat_union}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\sum\\limits_{i=0}^{k} \\left|{{\\hat{x}}_{i}}\\right| = n - \\left|{{x}_{j}}\\right| + \\left|{{x}_{j} \\setminus \\left\\{n\\right\\}}\\right| + 1}\\tag*{Eq[125]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\left|{{x}_{j} \\setminus \\left\\{n\\right\\}}\\right| = \\left|{{x}_{j}}\\right| - 1}}\\tag*{Eq[126]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\sum\\limits_{i=0}^{k} \\left|{{\\hat{x}}_{i}}\\right| = n}}\\tag*{Eq[127]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{\\hat{x}}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{\\hat{x}}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k} {\\hat{x}}_{i} = \\left[0; n\\right)}}\\tag*{Eq[128]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{{\\hat{x}}_{0:k + 1} \\in s'_{1}}}\\tag*{Eq.x_hat_in_s1}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\forall_{\\substack{0 \\le i \\le k}}{\\left|{{\\hat{x}}_{i}}\\right| > 0}\\wedge \\sum\\limits_{i=0}^{k} \\left|{{\\hat{x}}_{i}}\\right| = n\\wedge \\bigcup\\limits_{i=0}^{k} {\\hat{x}}_{i} = \\left[0; n\\right)}}\\tag*{Eq[128]}\\)";
$txt[$i++] = "\\({\\hat{x}}_{j} = {x}_{j} \\setminus \\left\\{n\\right\\}\\tag*{Eq[129]}\\)\\(\\forall_{\\substack{i \\left| i \\neq j \\right.}}{{\\hat{x}}_{i} = {x}_{i}}\\tag*{Eq[130]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\forall_{\\substack{i \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{{\\hat{x}}_{i} = {x}_{i} \\setminus \\left\\{n\\right\\}}}}\\tag*{Eq[131]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{j}{\\forall_{\\substack{0 \\le i \\le k}}{{\\hat{x}}_{i} = {x}_{i} \\setminus \\left\\{n\\right\\}}}}\\tag*{Eq[132]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{{\\hat{x}}_{0:k + 1} = [i:k + 1]{x}_{i} \\setminus \\left\\{n\\right\\}}\\tag*{Eq[133]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{[i:k + 1]{x}_{i} \\setminus \\left\\{n\\right\\} \\in s'_{1}}\\tag*{Eq[134]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s'_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j}}{{a}_{i} = {x'}_{i}}}\\tag*{Eq[135]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s'_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j}}{{a}_{i} = \\begin{cases} \\left\\{n\\right\\} \\cup {x}_{i} & \\text{if}\\: i = j \\\\{x}_{i} & \\text{else} \\end{cases}}}\\tag*{Eq[136]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s'_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{{a}_{i} \\setminus \\left\\{n\\right\\} = {x}_{i} \\setminus \\left\\{n\\right\\}}}\\tag*{Eq.equation}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{n\\right\\} \\cap \\bigcup\\limits_{i=0}^{k} {x}_{i} = \\emptyset}\\tag*{Eq[137]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{n\\right\\} \\cap {x}_{i} = \\emptyset}\\tag*{Eq.nonoverlapping_s1_quote}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}}}{{x}_{i} \\setminus \\left\\{n\\right\\} = {x}_{i}}\\tag*{Eq[138]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s'_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{{a}_{i} \\setminus \\left\\{n\\right\\} = {x}_{i}}}\\tag*{Eq[139]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{b \\in s'_{2, n}}}{\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{{b}_{i} \\setminus \\left\\{n\\right\\} = {x}_{i}}}\\tag*{Eq[139]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{b \\in s'_{2, n}}}{\\exists_{\\substack{a \\in s'_{1}}}{{b}_{i} \\setminus \\left\\{n\\right\\} = {a}_{i}}}\\tag*{Eq[140]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{\\exists_{\\substack{a \\in s'_{1}}}{{x}_{i} \\setminus \\left\\{n\\right\\} = {a}_{i}}}\\tag*{Eq[140]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{{x}_{0:k + 1} \\in s'_{2, n}}}{[i:k + 1]{x}_{i} \\setminus \\left\\{n\\right\\} \\in s'_{1}}\\tag*{Eq[134]}\\)";
$txt[$i++] = "\\(\\left|{s_{2}}\\right| = \\left(k + 1\\right) \\left|{s_{1}}\\right| + \\left|{s_{0}}\\right|\\tag*{?=>Eq.s2_abs_plausible}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\}\\supset \\bigcup_{j} {A}_{j}\\tag*{Eq.supset_A}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\not\\in e \\right\\} = \\bigcup_{j} {A}_{j}\\tag*{Eq[141]}\\)";
$txt[$i++] = "\\(\\left\\{e \\in s_{2} \\mid \\left\\{n\\right\\} \\in e \\right\\} = B\\tag*{Eq[142]}\\)";
$txt[$i++] = "\\(\\left|{s_{2}}\\right| = \\left|{B}\\right| + \\left|{\\bigcup_{j} {A}_{j}}\\right|\\tag*{Eq.s2_abs}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in B}}{\\exists_{\\substack{e \\in s_{0}}}{e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} = a}}\\tag*{Eq.B_assertion}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in B}}{\\exists_{\\substack{e \\in s_{0}}}{e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} = a \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq[143]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in B}}{e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{0}}\\tag*{Eq[144]}\\)";
$txt[$i++] = "\\(s_{0}\\supset \\left\\{\\left. e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in B \\right\\}\\tag*{Eq.s0_supset}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in B}}{e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\in s_{0}}\\tag*{Eq[144]}\\)";
$txt[$i++] = "\\(s_{0} \\subset \\left\\{\\left. e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in B \\right\\}\\tag*{Eq.s0_subset}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s_{0}}}{\\exists_{\\substack{e \\in B}}{a = e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq[145]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s_{0}}}{\\exists_{\\substack{e \\in B}}{a \\cup \\left\\{\\left\\{n\\right\\}\\right\\} = e \\cup \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq[146]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in s_{0}}}{e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\in B}\\tag*{Eq[147]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in B}}{\\left\\{\\left\\{n\\right\\}\\right\\} = e \\cap \\left\\{\\left\\{n\\right\\}\\right\\}}\\tag*{Eq[148]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{e \\in B}}{e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} = e}\\tag*{Eq[149]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s_{0}}}{a \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\in B}\\tag*{Eq[147]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s_{0}}}{\\exists_{\\substack{e \\in B}}{a \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} = e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq[150]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s_{0}}}{a \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} = a}\\tag*{Eq.s0_complement_n}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{a \\in s_{0}}}{\\exists_{\\substack{e \\in B}}{a = e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\}}}\\tag*{Eq[145]}\\)";
$txt[$i++] = "\\(s_{0} = \\left\\{\\left. e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in B \\right\\}\\tag*{Eq[151]}\\)";
$txt[$i++] = "\\(\\left|{\\left\\{\\left. e \\setminus \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in B \\right\\}}\\right| \\leq \\left|{B}\\right|\\tag*{Eq[152]}\\)";
$txt[$i++] = "\\(\\left|{s_{0}}\\right| \\leq \\left|{B}\\right|\\tag*{Eq[153]}\\)";
$txt[$i++] = "\\(\\left|{\\left\\{\\left. e \\cup \\left\\{\\left\\{n\\right\\}\\right\\} \\right| e \\in s_{0} \\right\\}}\\right| \\leq \\left|{s_{0}}\\right|\\tag*{Eq[154]}\\)";
$txt[$i++] = "\\(\\left|{B}\\right| \\leq \\left|{s_{0}}\\right|\\tag*{Eq[155]}\\)";
$txt[$i++] = "\\(\\left|{s_{0}}\\right| = \\left|{B}\\right|\\tag*{Eq[156]}\\)";
$txt[$i++] = "\\(\\left|{s_{2}}\\right| = \\left|{s_{0}}\\right| + \\left|{\\bigcup_{j} {A}_{j}}\\right|\\tag*{Eq[157]}\\)";
$txt[$i++] = "\\(\\left|{\\bigcup_{j} {A}_{j}}\\right| = \\left(k + 1\\right) \\left|{s_{1}}\\right|\\tag*{Eq.s2_abs_plausible=>Eq.A_union_abs}\\)";
$txt[$i++] = "\\(A' = [j]\\left\\{\\left\\{*x'\\right\\} \\right\\}\\tag*{Eq.A_quote_definition}\\)";
$txt[$i++] = "\\({A}_{j} = \\bigcup\\limits_{{x}_{0:k + 1} \\in s'_{1}} {A'}_{j}\\tag*{Eq.A_definition_simplified}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{{A'}_{j'} \\cap {A'}_{j} = \\emptyset}\\tag*{Eq.nonoverlapping}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{{A'}_{j'} \\cap {A'}_{j} \\neq \\emptyset}\\tag*{~Eq[158]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{k \\in {A'}_{j}\\\\j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{k \\in {A'}_{j'}}\\tag*{~Eq[159]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  \\in {A'}_{j'}}\\tag*{~Eq[160]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\left\\{*x'\\right\\}  = \\bigcup\\limits_{i=0}^{k} \\left\\{\\begin{cases} \\left\\{n\\right\\} \\cup {x}_{i} & \\text{if}\\: i = j' \\\\{x}_{i} & \\text{else} \\end{cases}\\right\\}}\\tag*{~Eq[161]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}\\\\{x}_{0:k + 1} \\in s'_{1}}}{\\forall_{\\substack{0 \\le i \\le k}}{\\begin{cases} \\left\\{n\\right\\} \\cup {x}_{i} & \\text{if}\\: i = j' \\\\{x}_{i} & \\text{else} \\end{cases} \\in \\left\\{*x'\\right\\} }}\\tag*{~Eq[162]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\left\\{n\\right\\} \\cup {x}_{j'} \\in \\left\\{*x'\\right\\} }\\tag*{~Eq[163]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}\\\\j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\left\\{n\\right\\} \\cup {x}_{j'} = {x'}_{i}}\\tag*{~Eq[164]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{0 \\le i \\le k\\\\{x}_{0:k + 1} \\in s'_{1}\\\\j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\left\\{n\\right\\} \\cup {x}_{j'} = \\begin{cases} \\left\\{n\\right\\} \\cup {x}_{i} & \\text{if}\\: i = j \\\\{x}_{i} & \\text{else} \\end{cases}}\\tag*{~Eq[165]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\left\\{n\\right\\} \\cup {x}_{j'} = \\left\\{n\\right\\} \\cup {x}_{j}}\\tag*{~Eq[166]}\\)\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}\\\\j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\forall_{\\substack{i \\left| i \\neq j \\right.}}{\\left\\{n\\right\\} \\cup {x}_{j'} = {x}_{i}}}\\tag*{~Eq[167]}\\)";
$txt[$i++] = "\\(\\exists_{\\substack{{x}_{0:k + 1} \\in s'_{1}}}{\\forall_{\\substack{i \\left| i \\neq j \\right.}}{\\left\\{n\\right\\} = \\left\\{n\\right\\} \\cap {x}_{i}}}\\tag*{~Eq[168]}\\)";
$txt[$i++] = "\\(\\text{False}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\bigcup\\limits_{{x}_{0:k + 1} \\in s'_{1}} {A'}_{j'} \\cap {A'}_{j} = \\emptyset}\\tag*{Eq[169]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{\\bigcup\\limits_{{x}_{0:k + 1} \\in s'_{1}} {A'}_{j'} \\cap \\bigcup\\limits_{{x}_{0:k + 1} \\in s'_{1}} {A'}_{j} = \\emptyset}\\tag*{Eq[170]}\\)";
$txt[$i++] = "\\({A}_{j'} = \\bigcup\\limits_{{x}_{0:k + 1} \\in s'_{1}} {A'}_{j'}\\tag*{Eq[171]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{j' \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{{A}_{j'} \\cap {A}_{j} = \\emptyset}\\tag*{Eq[172]}\\)";
$txt[$i++] = "\\(\\left|{\\bigcup_{j} {A}_{j}}\\right| = \\sum_{j} \\left|{{A}_{j}}\\right|\\tag*{?=>Eq[173]}\\)";
$txt[$i++] = "\\(\\forall_{\\substack{B \\in \\left[0; k\\right] \\setminus \\left\\{j\\right\\}}}{{A}_{B} \\cap {A}_{j} = \\emptyset}\\tag*{Eq[172]}\\)";
$txt[$i++] = "\\(\\sum_{j} \\left|{{A}_{j}}\\right| = \\left(k + 1\\right) \\left|{s_{1}}\\right|\\tag*{Eq[175]=>Eq[174]}\\)";
$txt[$i++] = "\\(\\left|{{A}_{j}}\\right| = \\left|{s_{1}}\\right|\\tag*{?=>Eq[175]}\\)";
$txt[$i++] = "\\(\\sum_{j} \\left|{{A}_{j}}\\right| = \\left(k + 1\\right) \\left|{s_{1}}\\right|\\tag*{Eq[175]=>Eq[174]}\\)";
render(__FILE__, $txt);
?>        

