<?php
require_once '..\..\..\utility.php';
$i = 0;
$txt[$i++] = "\\(Density\\left({\\color{red} {x_{0}}} + {\\color{red} {x_{1}}}\\right)\\left(y \\right) = \\frac{\\sqrt{2} {\\color{blue} e}^{- \\frac{\\left(- \\mu_{0} - \\mu_{1} + y\\right)^{2}}{2 \\sigma_{0}^{2} + 2 \\sigma_{1}^{2}}}}{2 \\sqrt{\\pi} \\sqrt{\\sigma_{0}^{2} + \\sigma_{1}^{2}}}\\tag*{Eq[0]}\\)";
$txt[$i++] = "\\(Density\\left({\\color{red} {x_{0}}} + {\\color{red} {x_{1}}}\\right)\\left(y \\right) = \\frac{\\int\\limits_{-\\infty}^{\\infty} {\\color{blue} e}^{- \\frac{\\left(- \\mu_{1} + x_{1}\\right)^{2}}{2 \\sigma_{1}^{2}}} \\int\\limits_{-\\infty}^{\\infty} {\\color{blue} e}^{- \\frac{\\left(- \\mu_{0} + x_{0}\\right)^{2}}{2 \\sigma_{0}^{2}}} \\delta\\left(x_{0} + x_{1} - y\\right)\\, dx_{0}\\, dx_{1}}{2 \\pi \\sigma_{0} \\sigma_{1}}\\tag*{Eq[1]}\\)";
$txt[$i++] = "\\(Density\\left({\\color{red} {x_{0}}} + {\\color{red} {x_{1}}}\\right)\\left(y \\right) = \\frac{{\\color{blue} e}^{- \\frac{\\mu_{0}^{2}}{2 \\sigma_{0}^{2}}} \\int\\limits_{-\\infty}^{\\infty} {\\color{blue} e}^{- \\frac{\\left(- x_{1} + y\\right)^{2}}{2 \\sigma_{0}^{2}}} {\\color{blue} e}^{- \\frac{\\left(- \\mu_{1} + x_{1}\\right)^{2}}{2 \\sigma_{1}^{2}}} {\\color{blue} e}^{\\frac{\\mu_{0} \\left(- x_{1} + y\\right)}{\\sigma_{0}^{2}}}\\, dx_{1}}{2 \\pi \\sigma_{0} \\sigma_{1}}\\tag*{Eq[2]}\\)";
$txt[$i++] = "\\(\\int\\limits_{-\\infty}^{\\infty} {\\color{blue} e}^{- \\frac{\\left(- x_{1} + y\\right)^{2}}{2 \\sigma_{0}^{2}}} {\\color{blue} e}^{- \\frac{\\left(- \\mu_{1} + x_{1}\\right)^{2}}{2 \\sigma_{1}^{2}}} {\\color{blue} e}^{\\frac{\\mu_{0} \\left(- x_{1} + y\\right)}{\\sigma_{0}^{2}}}\\, dx_{1} = \\frac{\\sqrt{2} \\sqrt{\\pi} \\sigma_{0} \\sigma_{1} {\\color{blue} e}^{- \\frac{- \\mu_{0}^{2} \\sigma_{1}^{2} + 2 \\mu_{0} \\mu_{1} \\sigma_{0}^{2} - 2 \\mu_{0} \\sigma_{0}^{2} y + \\mu_{1}^{2} \\sigma_{0}^{2} - 2 \\mu_{1} \\sigma_{0}^{2} y + \\sigma_{0}^{2} y^{2}}{2 \\sigma_{0}^{4} + 2 \\sigma_{0}^{2} \\sigma_{1}^{2}}}}{\\sqrt{\\sigma_{0}^{2} + \\sigma_{1}^{2}}}\\tag*{Eq[3]}\\)";
$txt[$i++] = "\\(Density\\left({\\color{red} {x_{0}}} + {\\color{red} {x_{1}}}\\right)\\left(y \\right) = \\frac{\\sqrt{2} {\\color{blue} e}^{- \\frac{\\mu_{0}^{2}}{2 \\sigma_{0}^{2}}} {\\color{blue} e}^{- \\frac{- \\mu_{0}^{2} \\sigma_{1}^{2} + 2 \\mu_{0} \\mu_{1} \\sigma_{0}^{2} - 2 \\mu_{0} \\sigma_{0}^{2} y + \\mu_{1}^{2} \\sigma_{0}^{2} - 2 \\mu_{1} \\sigma_{0}^{2} y + \\sigma_{0}^{2} y^{2}}{2 \\sigma_{0}^{4} + 2 \\sigma_{0}^{2} \\sigma_{1}^{2}}}}{2 \\sqrt{\\pi} \\sqrt{\\sigma_{0}^{2} + \\sigma_{1}^{2}}}\\tag*{Eq[4]}\\)";
$txt[$i++] = "\\({\\color{blue} e}^{- \\frac{\\mu_{0}^{2}}{2 \\sigma_{0}^{2}}} {\\color{blue} e}^{- \\frac{- \\mu_{0}^{2} \\sigma_{1}^{2} + 2 \\mu_{0} \\mu_{1} \\sigma_{0}^{2} - 2 \\mu_{0} \\sigma_{0}^{2} y + \\mu_{1}^{2} \\sigma_{0}^{2} - 2 \\mu_{1} \\sigma_{0}^{2} y + \\sigma_{0}^{2} y^{2}}{2 \\sigma_{0}^{4} + 2 \\sigma_{0}^{2} \\sigma_{1}^{2}}} = {\\color{blue} e}^{- \\frac{\\left(- \\mu_{0} - \\mu_{1} + y\\right)^{2}}{2 \\sigma_{0}^{2} + 2 \\sigma_{1}^{2}}}\\tag*{Eq[5]}\\)";
$txt[$i++] = "\\({\\color{blue} e}^{- \\frac{\\mu_{0}^{2}}{2 \\sigma_{0}^{2}}} {\\color{blue} e}^{\\frac{\\mu_{0}^{2}}{2 \\left(\\sigma_{0}^{2} + \\sigma_{1}^{2}\\right)}} {\\color{blue} e}^{\\frac{\\mu_{0}^{2} \\sigma_{1}^{2}}{2 \\sigma_{0}^{4} + 2 \\sigma_{0}^{2} \\sigma_{1}^{2}}} = 1\\tag*{Eq[6]}\\)";
$txt[$i++] = "\\(\\log{\\left({\\color{blue} e}^{- \\frac{\\mu_{0}^{2}}{2 \\sigma_{0}^{2}}} {\\color{blue} e}^{\\frac{\\mu_{0}^{2}}{2 \\left(\\sigma_{0}^{2} + \\sigma_{1}^{2}\\right)}} {\\color{blue} e}^{\\frac{\\mu_{0}^{2} \\sigma_{1}^{2}}{2 \\sigma_{0}^{4} + 2 \\sigma_{0}^{2} \\sigma_{1}^{2}}} \\right)} = 0\\tag*{Eq[7]}\\)";
$txt[$i++] = "\\(\\frac{\\mu_{0}^{2} \\sigma_{1}^{2}}{2 \\sigma_{0}^{4} + 2 \\sigma_{0}^{2} \\sigma_{1}^{2}} + \\frac{\\mu_{0}^{2}}{2 \\left(\\sigma_{0}^{2} + \\sigma_{1}^{2}\\right)} - \\frac{\\mu_{0}^{2}}{2 \\sigma_{0}^{2}} = 0\\tag*{Eq[8]}\\)";
$txt[$i++] = "\\(\\text{True}\\)";
render(__FILE__, $txt);
?>        

